version: '2'
services:
   nginx-reverse-proxy:
     image: nginx
     container_name: nginx-reverse-proxy
     restart: on-failure
     ports:
       - "80:80"
       - "443:443"
     volumes:
#       - ./../nginx-reversproxy/${CONFIGS_PROVIDER_NGINX_PROXY}/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./../nginx-reversproxy/run:/etc/nginx/conf.d:ro
       - ./../nginx-reversproxy/${CONFIGS_PROVIDER_NGINX_PROXY}/ssl:/etc/nginx/ssl
     networks:
       - docker_projectsubnetwork

networks:
       docker_projectsubnetwork:
         external: true
