version: '2'
services:
    web:
        image: ${CONTAINER_WEB_IMAGE}${PHP_VERSION}
        container_name: ${PROJECT_NAME}_${CONTAINER_WEB_NAME}
        environment:
          - USE_UNISON_SYNC=${USE_UNISON_SYNC}
        ports:
          - "${MACHINE_IP_ADDRESS}:{{nginx_port_dynamic}}:{{nginx_port_inner}}"
          - "{{unison_port_dynamic}}:{{unison_port_inner}}"
          - "{{ssh_port_dynamic}}:{{ssh_port_inner}}"
        volumes:
          - ./configs/nginx/${CONFIGS_PROVIDER_NGINX}/conf:/etc/nginx/conf.d
          - ./configs/php/${CONFIGS_PROVIDER_PHP}/ini/xdebug.ini:/etc/php/${PHP_VERSION}/mods-available/xdebug.ini
          - ./configs/php/${CONFIGS_PROVIDER_PHP}/ini/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini
          - ./configs/php/${CONFIGS_PROVIDER_PHP}/ini/zzz-custom.ini:/etc/php/${PHP_VERSION}/mods-available/zzz-custom.ini
          - ./../.env:/var/www/docker-config/.env
          - ./../.env-project.json:${PROJECT_CONFIGURATION_FILE}
          - ./../src:/var/www/src
          - ./../sysdumps/node_modules:/var/www/node_modules_remote
          - ./../../../${TOOLS_PROVIDER}:${TOOLS_PROVIDER_REMOTE_PATH}
          - ./../public_html/.git:${WEBSITE_DOCUMENT_ROOT}/.git
          - ./../../../configs/nginx-reversproxy/${CONFIGS_PROVIDER_NGINX_PROXY}/ssl:/etc/nginx/ssl
        networks:
          - docker_projectsubnetwork

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID_T}
            - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN_T}
            - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID_T}
            - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN_T}
        networks:
            - docker_projectsubnetwork

    db:
        image: mysql:${CONTAINER_MYSQL_VERSION}
        container_name: ${PROJECT_NAME}_${CONTAINER_MYSQL_NAME}
        ports:
          - "{{mysql_port_dynamic}}:{{mysql_port_inner}}"
        environment:
          - MYSQL_ROOT_PASSWORD=${CONTAINER_MYSQL_ROOT_PASS}
          - MYSQL_DATABASE=${CONTAINER_MYSQL_DB_NAME}
        volumes:
          - ./configs/mysql/${CONFIGS_PROVIDER_MYSQL}/db/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
          - docker_projectsubnetwork
        restart: on-failure

networks:
       docker_projectsubnetwork:
         external: true