version: '2'
services:
   portainer:
     image: portainer/portainer
     container_name: portainer
     restart: always
     ports:
       - "${MACHINE_IP_ADDRESS}:${PORTAINER_PORT}:9000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     command: --no-auth -H unix:///var/run/docker.sock
     networks:
       - projectsubnetwork

networks:
   projectsubnetwork:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
