version: '2'
services:
    redis:
         image: redis:4
         container_name: ${PROJECT_NAME}_${CONTAINER_REDIS_NAME}
         restart: always
         networks:
            - docker_projectsubnetwork

networks:
       docker_projectsubnetwork:
         external: true