version: '2'
services:
   mailhog:
    image: madebyewave/mailhog
    container_name: mailer
    restart: always
    ports:
      - "8025:8025"
    networks:
      - docker_projectsubnetwork

networks:
       docker_projectsubnetwork:
         external: true
