version: '2'
services:
  exim4:
    build: ./../exim4/
    image: ewave/exim4
    container_name: mailer
    volumes:
      - ./../exim4/config/exim4/:/etc/exim4
    networks:
      - docker_projectsubnetwork

networks:
       docker_projectsubnetwork:
         external: true
